// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cash_flow.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTotalInflowByPeriod = `-- name: GetTotalInflowByPeriod :one
SELECT COALESCE(SUM(total_amount), 0)::FLOAT AS total_inflow
FROM sales
WHERE company_id = $1
    AND created_at BETWEEN $2 AND $3
`

type GetTotalInflowByPeriodParams struct {
	CompanyID   pgtype.UUID        `json:"company_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetTotalInflowByPeriod(ctx context.Context, arg GetTotalInflowByPeriodParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalInflowByPeriod, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	var total_inflow float64
	err := row.Scan(&total_inflow)
	return total_inflow, err
}

const getTotalOutflowByPeriod = `-- name: GetTotalOutflowByPeriod :one
SELECT COALESCE(SUM(amount_paid), 0)::FLOAT AS total_outflow
FROM bills_payable
WHERE company_id = $1
    AND status = 'paid'
    AND payment_date BETWEEN $2 AND $3
`

type GetTotalOutflowByPeriodParams struct {
	CompanyID     pgtype.UUID `json:"company_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
}

func (q *Queries) GetTotalOutflowByPeriod(ctx context.Context, arg GetTotalOutflowByPeriodParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalOutflowByPeriod, arg.CompanyID, arg.PaymentDate, arg.PaymentDate_2)
	var total_outflow float64
	err := row.Scan(&total_outflow)
	return total_outflow, err
}
