// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	TradeName           pgtype.Text        `json:"trade_name"`
	Document            pgtype.Text        `json:"document"`
	DocumentType        pgtype.Text        `json:"document_type"`
	Email               pgtype.Text        `json:"email"`
	Phone               pgtype.Text        `json:"phone"`
	Website             pgtype.Text        `json:"website"`
	AddressStreet       pgtype.Text        `json:"address_street"`
	AddressNumber       pgtype.Text        `json:"address_number"`
	AddressComplement   pgtype.Text        `json:"address_complement"`
	AddressNeighborhood pgtype.Text        `json:"address_neighborhood"`
	AddressCity         pgtype.Text        `json:"address_city"`
	AddressState        pgtype.Text        `json:"address_state"`
	AddressZipcode      pgtype.Text        `json:"address_zipcode"`
	AddressCountry      pgtype.Text        `json:"address_country"`
	Status              interface{}        `json:"status"`
	Timezone            pgtype.Text        `json:"timezone"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Customer struct {
	ID                  pgtype.UUID        `json:"id"`
	CompanyID           pgtype.UUID        `json:"company_id"`
	FullName            string             `json:"full_name"`
	BirthDate           pgtype.Date        `json:"birth_date"`
	Cpf                 string             `json:"cpf"`
	Rg                  pgtype.Text        `json:"rg"`
	MaritalStatus       pgtype.Text        `json:"marital_status"`
	Gender              interface{}        `json:"gender"`
	Whatsapp            pgtype.Text        `json:"whatsapp"`
	MobilePhone         pgtype.Text        `json:"mobile_phone"`
	HomePhone           pgtype.Text        `json:"home_phone"`
	Email               string             `json:"email"`
	AddressStreet       pgtype.Text        `json:"address_street"`
	AddressNumber       pgtype.Text        `json:"address_number"`
	AddressComplement   pgtype.Text        `json:"address_complement"`
	AddressNeighborhood pgtype.Text        `json:"address_neighborhood"`
	AddressCity         pgtype.Text        `json:"address_city"`
	AddressState        pgtype.Text        `json:"address_state"`
	AddressZipcode      pgtype.Text        `json:"address_zipcode"`
	AddressCountry      pgtype.Text        `json:"address_country"`
	BalanceDue          pgtype.Numeric     `json:"balance_due"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Department struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Barcode     pgtype.Text        `json:"barcode"`
	Quantity    int32              `json:"quantity"`
	Size        pgtype.Text        `json:"size"`
	CostPrice   pgtype.Numeric     `json:"cost_price"`
	SalePrice   pgtype.Numeric     `json:"sale_price"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ProductCategory struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID pgtype.UUID        `json:"company_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	Status    interface{}        `json:"status"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Username     pgtype.Text        `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       interface{}        `json:"status"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
