// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	Username     pgtype.Text      `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	Status       interface{}      `json:"status"`
	CompanyID    pgtype.UUID      `json:"company_id"`
	DepartmentID pgtype.UUID      `json:"department_id"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
	CreatedBy    pgtype.UUID      `json:"created_by"`
	UpdatedBy    pgtype.UUID      `json:"updated_by"`
	DeletedBy    pgtype.UUID      `json:"deleted_by"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}
