// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCustomers(ctx context.Context, companyID pgtype.UUID) (int64, error)
	CountProducts(ctx context.Context, companyID pgtype.UUID) (int64, error)
	CountSales(ctx context.Context, companyID pgtype.UUID) (int64, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateCustomers(ctx context.Context, arg CreateCustomersParams) (pgtype.UUID, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (pgtype.UUID, error)
	CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementStock(ctx context.Context, arg DecrementStockParams) error
	DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error
	DeleteItemsBySale(ctx context.Context, saleID pgtype.UUID) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteProductCategory(ctx context.Context, arg DeleteProductCategoryParams) error
	DeleteSale(ctx context.Context, arg DeleteSaleParams) error
	DeleteSaleItem(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetCompanyByDocument(ctx context.Context, document pgtype.Text) (Company, error)
	GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error)
	GetCostTotalStock(ctx context.Context, companyID pgtype.UUID) (float64, error)
	GetCustomerByCPF(ctx context.Context, cpf string) (Customer, error)
	GetCustomerById(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetCustomersPerformanceSummary(ctx context.Context, companyID pgtype.UUID) (GetCustomersPerformanceSummaryRow, error)
	GetDepartmentById(ctx context.Context, id pgtype.UUID) (Department, error)
	GetProductByBarcode(ctx context.Context, barcode pgtype.Text) (Product, error)
	GetProductById(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductCategoryById(ctx context.Context, id pgtype.UUID) (ProductCategory, error)
	GetProductsPerformanceSummary(ctx context.Context, companyID pgtype.UUID) (GetProductsPerformanceSummaryRow, error)
	GetSaleById(ctx context.Context, arg GetSaleByIdParams) (GetSaleByIdRow, error)
	GetSaleByIdWhatsapp(ctx context.Context, id pgtype.UUID) (GetSaleByIdWhatsappRow, error)
	GetSalesPerformanceSummary(ctx context.Context, companyID pgtype.UUID) (GetSalesPerformanceSummaryRow, error)
	GetTotalAmountByStatus(ctx context.Context, arg GetTotalAmountByStatusParams) (float64, error)
	GetTotalAmountSummary(ctx context.Context, companyID pgtype.UUID) (GetTotalAmountSummaryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	ListCustomers(ctx context.Context, companyID pgtype.UUID) ([]Customer, error)
	ListDepartmentsByCompanyId(ctx context.Context, companyID pgtype.UUID) ([]Department, error)
	ListItemsFromPendingSale(ctx context.Context, saleID pgtype.UUID) ([]ListItemsFromPendingSaleRow, error)
	ListProductCategoryByCompanyId(ctx context.Context, companyID pgtype.UUID) ([]ProductCategory, error)
	ListProductsByCategoryId(ctx context.Context, arg ListProductsByCategoryIdParams) ([]Product, error)
	ListProductsByCompany(ctx context.Context, companyID pgtype.UUID) ([]ListProductsByCompanyRow, error)
	ListSales(ctx context.Context, companyID pgtype.UUID) ([]ListSalesRow, error)
	ListSalesByCompanyAndStatus(ctx context.Context, arg ListSalesByCompanyAndStatusParams) ([]ListSalesByCompanyAndStatusRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	SetCompanyStatus(ctx context.Context, arg SetCompanyStatusParams) (int64, error)
	SetProductCategoryStatus(ctx context.Context, arg SetProductCategoryStatusParams) (int64, error)
	SetStatusDepartment(ctx context.Context, arg SetStatusDepartmentParams) (int64, error)
	UpdateBalanceDueCustomer(ctx context.Context, arg UpdateBalanceDueCustomerParams) error
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateOverdueSales(ctx context.Context) ([]pgtype.UUID, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
	UpdateSaleStatus(ctx context.Context, arg UpdateSaleStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserCompanyAndRole(ctx context.Context, arg UpdateUserCompanyAndRoleParams) error
}

var _ Querier = (*Queries)(nil)
