// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
    customer_id, 
    company_id, 
    sale_at, 
    discount_amount, 
    subtotal, 
    total_amount, 
    created_by,
    status
) VALUES (
    $1, $2, CURRENT_DATE, $3, $4, $5, $6, 'pending'
) RETURNING id
`

type CreateSaleParams struct {
	CustomerID     pgtype.UUID    `json:"customer_id"`
	CompanyID      pgtype.UUID    `json:"company_id"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.CustomerID,
		arg.CompanyID,
		arg.DiscountAmount,
		arg.Subtotal,
		arg.TotalAmount,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSale = `-- name: DeleteSale :exec
UPDATE sales 
SET 
    deleted_at = CURRENT_TIMESTAMP, 
    deleted_by = $1 
WHERE id = $2 AND company_id = $3
`

type DeleteSaleParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) DeleteSale(ctx context.Context, arg DeleteSaleParams) error {
	_, err := q.db.Exec(ctx, deleteSale, arg.DeletedBy, arg.ID, arg.CompanyID)
	return err
}

const getSaleById = `-- name: GetSaleById :one
SELECT 
    s.id, s.customer_id, s.company_id, s.sale_at, s.discount_amount, s.subtotal, s.total_amount, s.due_days, s.payment_method, s.status, s.created_at, s.created_by, s.updated_at, s.updated_by, s.deleted_at, s.deleted_by, 
    c.full_name as customer_name 
FROM sales s
INNER JOIN customers c ON s.customer_id = c.id
WHERE s.id = $1 AND s.company_id = $2
`

type GetSaleByIdParams struct {
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

type GetSaleByIdRow struct {
	ID             pgtype.UUID        `json:"id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	CompanyID      pgtype.UUID        `json:"company_id"`
	SaleAt         pgtype.Timestamptz `json:"sale_at"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	DueDays        pgtype.Int4        `json:"due_days"`
	PaymentMethod  interface{}        `json:"payment_method"`
	Status         interface{}        `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	CustomerName   string             `json:"customer_name"`
}

func (q *Queries) GetSaleById(ctx context.Context, arg GetSaleByIdParams) (GetSaleByIdRow, error) {
	row := q.db.QueryRow(ctx, getSaleById, arg.ID, arg.CompanyID)
	var i GetSaleByIdRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.SaleAt,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.TotalAmount,
		&i.DueDays,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CustomerName,
	)
	return i, err
}

const listSales = `-- name: ListSales :many
SELECT 
    id, sale_at, total_amount, status, created_at 
FROM sales 
WHERE company_id = $1 
  AND deleted_at IS NULL 
ORDER BY created_at DESC
`

type ListSalesRow struct {
	ID          pgtype.UUID        `json:"id"`
	SaleAt      pgtype.Timestamptz `json:"sale_at"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Status      interface{}        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSales(ctx context.Context, companyID pgtype.UUID) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRow{}
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleAt,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaleStatus = `-- name: UpdateSaleStatus :exec
UPDATE sales 
SET 
    status = $1, 
    updated_at = CURRENT_TIMESTAMP, 
    updated_by = $2 
WHERE id = $3 AND company_id = $4
`

type UpdateSaleStatusParams struct {
	Status    interface{} `json:"status"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) UpdateSaleStatus(ctx context.Context, arg UpdateSaleStatusParams) error {
	_, err := q.db.Exec(ctx, updateSaleStatus,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
	)
	return err
}
