// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
        customer_id,
        company_id,
        sale_at,
        discount_amount,
        subtotal,
        total_amount,
        created_by,
        status
    )
VALUES (
        $1,
        $2,
        CURRENT_DATE,
        $3,
        $4,
        $5,
        $6,
        'pending'
    )
RETURNING id
`

type CreateSaleParams struct {
	CustomerID     pgtype.UUID    `json:"customer_id"`
	CompanyID      pgtype.UUID    `json:"company_id"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.CustomerID,
		arg.CompanyID,
		arg.DiscountAmount,
		arg.Subtotal,
		arg.TotalAmount,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSale = `-- name: DeleteSale :exec
UPDATE sales
SET deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $1
WHERE id = $2
    AND company_id = $3
`

type DeleteSaleParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) DeleteSale(ctx context.Context, arg DeleteSaleParams) error {
	_, err := q.db.Exec(ctx, deleteSale, arg.DeletedBy, arg.ID, arg.CompanyID)
	return err
}

const getSaleById = `-- name: GetSaleById :one
SELECT s.id, s.customer_id, s.company_id, s.sale_at, s.discount_amount, s.subtotal, s.total_amount, s.due_days, s.payment_method, s.status, s.created_at, s.created_by, s.updated_at, s.updated_by, s.deleted_at, s.deleted_by,
    c.full_name as customer_name
FROM sales s
    INNER JOIN customers c ON s.customer_id = c.id
WHERE s.id = $1
    AND s.company_id = $2
`

type GetSaleByIdParams struct {
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

type GetSaleByIdRow struct {
	ID             pgtype.UUID        `json:"id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	CompanyID      pgtype.UUID        `json:"company_id"`
	SaleAt         pgtype.Timestamptz `json:"sale_at"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	DueDays        pgtype.Int4        `json:"due_days"`
	PaymentMethod  interface{}        `json:"payment_method"`
	Status         interface{}        `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	CustomerName   string             `json:"customer_name"`
}

func (q *Queries) GetSaleById(ctx context.Context, arg GetSaleByIdParams) (GetSaleByIdRow, error) {
	row := q.db.QueryRow(ctx, getSaleById, arg.ID, arg.CompanyID)
	var i GetSaleByIdRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.SaleAt,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.TotalAmount,
		&i.DueDays,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CustomerName,
	)
	return i, err
}

const listSales = `-- name: ListSales :many
SELECT id,
    sale_at,
    total_amount,
    status,
    created_at
FROM sales
WHERE company_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListSalesRow struct {
	ID          pgtype.UUID        `json:"id"`
	SaleAt      pgtype.Timestamptz `json:"sale_at"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Status      interface{}        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSales(ctx context.Context, companyID pgtype.UUID) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRow{}
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleAt,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByCompanyAndStatus = `-- name: ListSalesByCompanyAndStatus :many
SELECT s.id AS sale_id,
    s.total_amount,
    s.discount_amount,
    s.status,
    s.sale_at,
    s.created_at AS sale_date,
    si.id AS item_id,
    si.product_id,
    si.quantity,
    si.unit_price,
    si.discount,
    p.name AS product_name,
    c.full_name AS customer_name
FROM sales s
    INNER JOIN customers c ON s.customer_id = c.id
    INNER JOIN sale_items si ON s.id = si.sale_id
    INNER JOIN products p ON si.product_id = p.id
WHERE s.company_id = $1
    AND (
        ($2::text IS NULL OR $2::text = '')
        OR s.status::text = $2::text
    )
ORDER BY s.created_at DESC
`

type ListSalesByCompanyAndStatusParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Column2   string      `json:"column_2"`
}

type ListSalesByCompanyAndStatusRow struct {
	SaleID         pgtype.UUID        `json:"sale_id"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	Status         interface{}        `json:"status"`
	SaleAt         pgtype.Timestamptz `json:"sale_at"`
	SaleDate       pgtype.Timestamptz `json:"sale_date"`
	ItemID         pgtype.UUID        `json:"item_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	Quantity       int32              `json:"quantity"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Discount       pgtype.Numeric     `json:"discount"`
	ProductName    string             `json:"product_name"`
	CustomerName   string             `json:"customer_name"`
}

func (q *Queries) ListSalesByCompanyAndStatus(ctx context.Context, arg ListSalesByCompanyAndStatusParams) ([]ListSalesByCompanyAndStatusRow, error) {
	rows, err := q.db.Query(ctx, listSalesByCompanyAndStatus, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesByCompanyAndStatusRow{}
	for rows.Next() {
		var i ListSalesByCompanyAndStatusRow
		if err := rows.Scan(
			&i.SaleID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.Status,
			&i.SaleAt,
			&i.SaleDate,
			&i.ItemID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Discount,
			&i.ProductName,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaleStatus = `-- name: UpdateSaleStatus :exec
UPDATE sales
SET status = $1,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE id = $3
    AND company_id = $4
`

type UpdateSaleStatusParams struct {
	Status    interface{} `json:"status"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) UpdateSaleStatus(ctx context.Context, arg UpdateSaleStatusParams) error {
	_, err := q.db.Exec(ctx, updateSaleStatus,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
	)
	return err
}
