// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sale_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSaleItem = `-- name: CreateSaleItem :exec
INSERT INTO sale_items (
        sale_id,
        product_id,
        quantity,
        unit_price,
        discount
    )
VALUES ($1, $2, $3, $4, $5)
`

type CreateSaleItemParams struct {
	SaleID    pgtype.UUID    `json:"sale_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	Discount  pgtype.Numeric `json:"discount"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) error {
	_, err := q.db.Exec(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.Discount,
	)
	return err
}

const deleteItemsBySale = `-- name: DeleteItemsBySale :exec
DELETE FROM sale_items
WHERE sale_id = $1
`

func (q *Queries) DeleteItemsBySale(ctx context.Context, saleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemsBySale, saleID)
	return err
}

const deleteSaleItem = `-- name: DeleteSaleItem :exec
DELETE FROM sale_items
WHERE id = $1
`

func (q *Queries) DeleteSaleItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSaleItem, id)
	return err
}

const listItemsFromPendingSale = `-- name: ListItemsFromPendingSale :many
SELECT si.id,
    si.sale_id,
    si.product_id,
    si.quantity,
    si.unit_price,
    si.discount,
    p.name as product_name
FROM sale_items si
    INNER JOIN sales s ON si.sale_id = s.id
    INNER JOIN products p ON si.product_id = p.id
WHERE si.sale_id = $1
    AND s.status = 'PENDING'
`

type ListItemsFromPendingSaleRow struct {
	ID          pgtype.UUID    `json:"id"`
	SaleID      pgtype.UUID    `json:"sale_id"`
	ProductID   pgtype.UUID    `json:"product_id"`
	Quantity    int32          `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Discount    pgtype.Numeric `json:"discount"`
	ProductName string         `json:"product_name"`
}

func (q *Queries) ListItemsFromPendingSale(ctx context.Context, saleID pgtype.UUID) ([]ListItemsFromPendingSaleRow, error) {
	rows, err := q.db.Query(ctx, listItemsFromPendingSale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsFromPendingSaleRow{}
	for rows.Next() {
		var i ListItemsFromPendingSaleRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Discount,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
